services:
  splitgram-app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Rome
    env_file:
      - .env
    restart: unless-stopped

networks:
  cloudflared:
    external: true